# Define stages, build the module, then try to install and use
stages:
  - unit_test
  - build_test

# Default settings for all jobs
# Disable sudo to speed up the build
sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

# Actual jobs
jobs:
  include:
    - stage: unit_test
      os:
        - linux
        - osx
      install:
        - pip install codecov
        - pip install -r requirements.txt
      script:
        - python -m pytest --cov=truegaze/
      after_success:
        - codecov

    - stage: build_test
      os:
        - linux
        - osx
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py sdist bdist_wheel
        - pip install dist/truegaze-*.whl
        - truegaze scan test_data/helloworld.apk
        - truegaze scan test_data/helloworld.ipa
