# Disable sudo to speed up the build
sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.8"
  - "nightly"
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - python -m pytest --cov=truegaze/
after_success:
  - codecov