name: Test package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.9, nightly]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python -m pytest --cov=truegaze/
        codecov
    - name: Test package build and install
      run: |
        python setup.py sdist bdist_wheel
        pip install dist/truegaze-*.whl
        truegaze scan test_data/helloworld.apk
        truegaze scan test_data/helloworld.ipa
